# Defining Trends
### Overview of Trends 
### Innovations
### Games
### Graphs
This chapter tells the story of "trends" for digital networks. This chapter starts with a very simple definition of a trend according to Diffusion of Innovations, explaining the S-shaped model of diffusion, and the "Justin Bieber" problem. It then complicates this definition with discussions of "contagion" effects, and the problem of defining trends within singular networks.

Moving forward, it looks at the question of "trends" for game theory, explaining some fundamental issues related to information cascades, the unintended consequences of "datafication" (the 'like' button, for example), and then other issues--such as the common practice of 'gaming' social network algorithms. The goal for this chapter is to continue complicating the idea of "trends," and to have the concept evolve as we work our way through Diffusion of Innovations, and then game theory, and then finally into graphs and other issues.

For graph theory we discuss strong and weak ties, triadic closure, and other known phenomenon resulting from agent based modeling. Additionally, we can bring in other ideas, like metcalfe's law and the dunbar number to also provide competing perspectives on how we make sense of patters/trends in digital networks.

**Chapter 4 Notes**
- What is a trend?
  - Diffusion of innovations terminologies
  - S-shaped curve of innovation
  - the "newness" problem
- How "game theory" complicates any simple notions of "trends" and virality
  - weak/strong ties
  - triadic closure
  - others?
- Graphs, agents, and blackboxes
- Others?
  - metcalfe's law
  - dunbar's number
- Information Cascades and Feedback Loops
