# Research Ethics
## Overview of Research Ethics
XXX this chapter combines the previously separated chapters: "Best Practices" and "Research Ethics" XXX
## Privacy Rights
## Intellectual Property
## Algorithms and Network Systems
## Open Access

This chapter explains the underlying rationale for MassMine: the use Application Programming Interfaces (APIs) to collect data from digital networks. Building on a basic description of API scraping, as compared to web scraping and web crawling, Chapter 1 explains the benefits and
limitations of API scraping for interdisciplinary research.

**Chapter Notes**
- Being a Good Citizen
- What is Data Mining?
  - A Brief History of Internet Research
  - Web crawling vs. web scraping vs. APIs vs. Semantic web
  - Big Data vs. Data Science
- Best Practices
  - Avoid Pitfalls
    - Accidental DDOS
    - Unintended Doxing
  - Respect robot.txt
  - Understand API limitations and developer guidelines for each network you research
    - Twitter "no benchmarking" example
  - Track the evolving ethics and legalities surrounding data mining (discussed at length in chapter 3)
- Follow scientific best practices (the subject of this book, also philosophy of interdisciplinary science chapter 8)
XXX
This chapter addresses the many ethical and ownership issues surrounding data mining activities as they relate to interdisciplinary research. Focusing on two primary areas--privacy rights and intellectual property--this chapter examines key areas related to data collection, anonimization, and ownership.
XXX
- Privacy rights--why they matter
  - Respond to this faulty logic:
    - "If you're not doing anything wrong, then you shouldn't have anything to hide."
- the limitations of "anonymous" data
- intellectual property law and web scraping
- Open access
  - the importance of the open data movement for interdisciplinary data mining
    - replicating studies/methods
    - archiving
    - data loss
  - legal issues involved with sharing data collected from APIs
  - database, storage, and archiving approaches
