---
title: "Network Macroscopes"
subtitle: "Data Mining Methodologies for Social Media and Digital Content"
author: "Aaron Beveridge and Nicholas M. Van Horn"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction {-}
This book is written as the companion text for MassMine, a free and open source research software. As the co-creators of MassMine, we have decided it would be irresponsible to merely produce a "textbook" or "how-to guide" for MassMine, because there are many difficult methodological and ethical concerns involved in researching social media and digital content. Because MassMine's community of users come from a diverse range of research disciplines (humanities, psychology, social sciences, technical communication, and business), this text is written to address a broad interdisciplinary audience when confronting the crucial methodological and ethical concerns. To this end, we have written *Network Macroscopes* with the three following goals in mind: (1) to establish best practices and ethical guidelines for research, (2) to explore key methodological areas for developing research questions and establishing interdisciplinary studies, and (3) to provide pragmatic techniques and accessible methods for collecting, sharing, and exporting data. Drawing heavily on natural language processing, graph and game theory, diffusion of innovations, and exploratory statistics, we have written *Network Macroscopes* to facilitate mixed-methods studies of social media activity and digital content. Indeed, this book argues that the best way to make sense of how evolving technologies like social media continue to influence culture, politics, businesses, social groups, and individuals is by reaching across these categories and their respective disciplines to increase the resolution through which we visualize the influence and effects of these technologies. While it certainly takes more than one book (and more than one software) to accomplish such a task, the best practices and research methodologies outlined in this book provide a tangible common ground--and starting point--for the students, faculty, and non-academics who are interested in becoming practitioners of interdisciplinary data mining.

Because this book has been written in R markdown, all of the example data visualizations in the methodologies section (Section II) also serve as functioning code examples to support readers in conducting their own studies. Each chapter provides suggested readings and tutorials to assist researchers in reproducing similar data visualizations for their own projects, and all of the code examples are available through GitHub. Additionally, the introduction will address why we have organized the book the way we have, providing a rationale for our choices and providing alternative ways of exploring the content in the book.
